//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedro_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurante
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public System.DateTime dt_cadastro { get; set; }
    }
}
